name: Workflow Manual

on:
  workflow_dispatch:
    inputs:
      mensaje:
        description: 'Mensaje a imprimir'
        required: true
        default: 'Hola mundo'
        type: string

jobs:
  imprimir-mensaje:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "${{ github.event.inputs.mensaje }}"
